name       : haskell-aeson-pretty
version    : 0.8.8
release    : 4
source     :
    - https://hackage.haskell.org/package/aeson-pretty-0.8.8/aeson-pretty-0.8.8.tar.gz : 81cea61cb6dcf32c3f0529ea5cfc98dbea3894152d7f2d9fe1cb051f927ec726
license    : BSD-3-Clause
component  : programming.haskell
summary    : A JSON pretty-printing library compatible with aeson as well as a command-line tool to improve readabilty of streams of JSON data.
description: |
    A JSON pretty-printing library compatible with aeson as well as a command-line tool to improve readabilty of streams of JSON data.
builddeps  :
    - haskell-aeson-devel
    - haskell-base-orphans-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - haskell-aeson-devel
        - haskell-base-orphans-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
