name       : haskell-aeson-pretty
version    : 0.8.7
release    : 3
source     :
    - https://hackage.haskell.org/package/aeson-pretty-0.8.7/aeson-pretty-0.8.7.tar.gz : c1c1ecc5e3abd004a6c4c256ee6f61da2a43d7f1452ffa391dee250df43b27d5
license    : BSD-3-Clause
component  : programming.haskell
summary    : A JSON pretty-printing library compatible with aeson as well as a command-line tool to improve readabilty of streams of JSON data.
description: |
    A JSON pretty-printing library compatible with aeson as well as a command-line tool to improve readabilty of streams of JSON data.
builddeps  :
    - haskell-aeson
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |-
    %cabal_install
    %cabal_register
