name       : haskell-aeson-pretty
version    : 0.8.5
release    : 1
source     :
    - https://hackage.haskell.org/package/aeson-pretty-0.8.5/aeson-pretty-0.8.5.tar.gz : dd17e86c64b3fe2efb7a855b27b0e5490e42dc58194ae1809d8b662d4e42a9f9
license    : BSD-3-Clause
component  : programming.haskell
summary    : A JSON pretty-printing library compatible with aeson as well as a command-line tool to improve readabilty of streams of JSON data.
description: |
    A JSON pretty-printing library compatible with aeson as well as a command-line tool to improve readabilty of streams of JSON data.
builddeps  :
    - haskell-aeson
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
